// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhkLpwGcpZXp3hyale9shJBT2Upz8XGEQ',
    appId: '1:755405588480:web:706f06d2b9cf596d43b0e5',
    messagingSenderId: '755405588480',
    projectId: 'honest-academy',
    authDomain: 'honest-academy.firebaseapp.com',
    storageBucket: 'honest-academy.firebasestorage.app',
    measurementId: 'G-8CVD99YQRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVLzz8KVMPu_DsJ5n63--2R1GevI8s85o',
    appId: '1:755405588480:android:6a07a46e86be2c2543b0e5',
    messagingSenderId: '755405588480',
    projectId: 'honest-academy',
    storageBucket: 'honest-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq87qVQmIW3TbMGk4u_NGISf2Q0Z8mELs',
    appId: '1:755405588480:ios:cffaac29ddceff6b43b0e5',
    messagingSenderId: '755405588480',
    projectId: 'honest-academy',
    storageBucket: 'honest-academy.firebasestorage.app',
    iosBundleId: 'com.example.honsetApp',
  );
}
